/// Flutter icons EmojiIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EmojiIcons
///      fonts:
///       - asset: fonts/EmojiIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EmojiIcons {
  EmojiIcons._();

  static const _kFontFam = 'EmojiIcons';

  static const IconData awful = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bad = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData excellent = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData good = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData moderate = const IconData(0xe804, fontFamily: _kFontFam);
}
