/// Flutter icons HomeIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeIcon
///      fonts:
///       - asset: fonts/HomeIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeIcon {
  HomeIcon._();

  static const _kFontFam = 'HomeIcon';

  static const IconData diary = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData target = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData test = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData conversation = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData calm = const IconData(0xe806, fontFamily: _kFontFam);
}
