/// Flutter icons HomeIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeIcons
///      fonts:
///       - asset: fonts/HomeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeIcons {
  HomeIcons._();

  static const _kFontFam = 'HomeIcons';

  static const IconData test = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData conversation = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData target = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData diary = const IconData(0xe804, fontFamily: _kFontFam);
}
